version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - ./db/:/data/db
  katana:
    depends_on:
      - mongodb
    container_name: card-game
    env_file:
        - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8083:8083
    restart: "on-failure"
